[package]
name = "virtualtable"
version = "0.1.0"
authors = ["scerelli <info@stefanocerelli.com>"]

[dependencies]
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
ws = "0.6.0"
lazy_static = "0.1"
